export const DUMMY_JOBS = [
  {
    id: 1,
    title: 'Software Engineer',
    location: 'Silicon Valley, CA',
    salary: 90000,
    experience: 3,
    companyName: 'Tech Innovators Inc.',
    companyWebsite: 'www.techinnovators.com',
    companyEmail: 'careers@techinnovators.com',
    jobCategory: 'Information Technology',
    jobType: 'Full-time',
    requiredSkills: ['Java', 'Python', 'JavaScript', 'Agile Development'],
    benefits: ['Health insurance', '401(k)', 'Flexible working hours'],
    keywords: ['Software Development', 'Backend', 'Frontend', 'Web Development'],
    logo: 'logo_url',
    addDate: 'July 9, 2023',
    description: 'We are seeking a skilled and experienced Software Engineer to join our team. As a Software Engineer, you will be responsible for developing high-quality software solutions and collaborating with cross-functional teams. You should have a strong background in Java, Python, and JavaScript, along with experience in Agile Development methodologies. Join us in shaping the future of technology!',
  },
  {
    id: 2,
    title: 'Marketing Coordinator',
    location: 'New York, NY',
    salary: 55000,
    experience: 1,
    companyName: 'Global Marketing Solutions',
    companyWebsite: 'www.globalmarketingsolutions.com',
    companyEmail: 'hr@globalmarketingsolutions.com',
    jobCategory: 'Marketing',
    jobType: 'Full-time',
    requiredSkills: ['Social media management', 'Content creation', 'SEO', 'Google Analytics'],
    benefits: ['Paid time off', 'Dental and Vision insurance', 'Professional development opportunities'],
    keywords: ['Marketing Strategy', 'Digital Marketing', 'Campaign Management'],
    logo: 'logo_url',
    addDate: 'July 7, 2023',
    description: 'We are looking for a talented Marketing Coordinator to join our dynamic marketing team. As a Marketing Coordinator, you will be responsible for executing marketing campaigns, managing social media platforms, creating engaging content, and analyzing marketing data. If you have a passion for marketing and possess skills in social media management, SEO, and content creation, we would love to hear from you!',
  },
  {
    id: 3,
    title: 'Graphic Designer (Remote)',
    location: 'Remote',
    salary: 50000,
    experience: 2,
    companyName: 'Creative Designs Ltd.',
    companyWebsite: 'www.creativedesigns.com',
    companyEmail: 'jobs@creativedesigns.com',
    jobCategory: 'Design',
    jobType: 'Full-time',
    requiredSkills: ['Adobe Creative Suite', 'UI/UX Design', 'Branding', 'Illustration'],
    benefits: ['Remote work', 'Health benefits', 'Flexible schedule'],
    keywords: ['Visual Design', 'Print Design', 'Logo Design'],
    logo: 'logo_url',
    addDate: 'July 5, 2023',
    description: 'Join our team as a Graphic Designer and showcase your creativity! As a Graphic Designer, you will be responsible for creating visually appealing designs for various platforms, including digital and print media. Proficiency in Adobe Creative Suite, UI/UX Design principles, branding, and illustration is essential. This is a remote position that offers a flexible schedule and great benefits.',
  },
  {
    id: 4,
    title: 'Sales Representative',
    location: 'Chicago, IL',
    salary: 0, // Commission-based + Bonuses
    experience: 0, // Entry level
    companyName: 'Sales Solutions Inc.',
    companyWebsite: 'www.salessolutions.com',
    companyEmail: 'careers@salessolutions.com',
    jobCategory: 'Sales',
    jobType: 'Full-time',
    requiredSkills: ['Excellent communication skills', 'Sales prospecting', 'Customer relationship management'],
    benefits: ['Uncapped earning potential', 'Sales training program', 'Travel opportunities'],
    keywords: ['B2B Sales', 'Client Acquisition', 'Negotiation'],
    logo: 'logo_url',
    addDate: 'July 3, 2023',
    description: 'Are you a passionate and driven individual looking to kick-start your career in sales? Join our team as a Sales Representative! In this role, you will engage with potential clients, build relationships, and drive sales for our products/services. While prior experience is not required, excellent communication skills and a strong desire to succeed are essential. Enjoy uncapped earning potential, a comprehensive sales training program, and exciting travel opportunities!',
  },
  {
    id: 5,
    title: 'Data Analyst Intern',
    location: 'San Francisco, CA',
    salary: 0, // Paid internship
    experience: 0, // No prior experience required
    companyName: 'Analytics Pro',
    companyWebsite: 'www.analyticspro.com',
    companyEmail: 'internships@analyticspro.com',
    jobCategory: 'Internship',
    jobType: 'Part-time',
    requiredSkills: ['Excel', 'SQL', 'Data visualization', 'Statistical analysis'],
    benefits: ['Mentorship program', 'Networking opportunities', 'Flexible schedule'],
    keywords: ['Data Analytics', 'Data Mining', 'Data Interpretation'],
    logo: 'logo_url',
    addDate: 'June 30, 2023',
    description: 'Embark on an exciting journey in the field of data analysis as a Data Analyst Intern! As an intern, you will gain hands-on experience in analyzing data, creating visualizations, and interpreting statistical findings. Proficiency in Excel, SQL, and data visualization tools is desired. This part-time internship offers a flexible schedule, mentorship opportunities, and the chance to network with industry professionals.',
  }
];
